spring:
  application :
     name: eureka-service


eureka :
  client:
    registerWithEureka : false
    fetchRegistry: false
    server:
       waitTimeInMsWhenSyncEmpty : 0


server :
   port : 8304


zuul :
  prefix : /api
  routes :
     database-service :
        path : /database-service/**
        url : http://localhost:8300
     stock-service :
        path : /stock-service/**
        url :  http//localhost:8301